
services:
  app:
    build: .
    container_name: rag-flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./temp_uploads:/app/temp_uploads
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FLASK_ENV=production
    depends_on:
      - ollama  #ensures Flask starts after Ollama.
    command: python app.py

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
